fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
    epel: "https://github.com/stahnma/puppet-module-epel.git"
    zypprepo: "https://github.com/deadpoint/puppet-zypprepo.git"
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
