---
fixtures:
  repositories:
    apt: https://github.com/puppetlabs/puppetlabs-apt.git
    archive: https://github.com/voxpupuli/puppet-archive.git
    epel: https://github.com/voxpupuli/puppet-epel.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
    zypprepo: https://github.com/deadpoint/puppet-zypprepo.git
